# Generated by Django 3.0.7 on 2020-06-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
