# Generated by Django 3.0.7 on 2020-06-16 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Micropackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Package')),
            ],
        ),
    ]
