# Generated by Django 3.0.7 on 2020-06-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_micropackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packagetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('micropackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Micropackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Product')),
            ],
        ),
    ]
